//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATOMv0.AuthenticationService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://flexware.flextronics.com/ws/client/faults/")]
    public partial class InvalidRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="user-master-ws", Namespace="http://flexware.flextronics.com/ws/client/authentication")]
    public partial class usermasterws : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userIdField;
        
        private string userNameField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("firstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("lastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="flexware-token-ws", Namespace="http://flexware.flextronics.com/ws/client/authentication")]
    public partial class flexwaretokenws : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://flexware.flextronics.com/ws/client/faults/")]
    public partial class InvalidToken : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://flexware.flextronics.com/ws/client/faults/")]
    public partial class ServiceFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://flexware.flextronics.com/ws/client/faults/")]
    public partial class InvalidCredentials : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://flexware.flextronics.com/ws/client/faults/")]
    public partial class AccessDenied : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://flexware.flextronics.com/ws/client/authentication", ConfigurationName="AuthenticationService.authenticationPort")]
    public interface authenticationPort {
        
        // CODEGEN: Parameter 'substituteUser' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="getSubstituteUser", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATOMv0.AuthenticationService.InvalidRequest), Action="getSubstituteUser", Name="InvalidRequest", Namespace="http://flexware.flextronics.com/ws/client/faults/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATOMv0.AuthenticationService.InvalidToken), Action="getSubstituteUser", Name="InvalidToken", Namespace="http://flexware.flextronics.com/ws/client/faults/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATOMv0.AuthenticationService.ServiceFault), Action="getSubstituteUser", Name="ServiceFault", Namespace="http://flexware.flextronics.com/ws/client/faults/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="substituteUser")]
        ATOMv0.AuthenticationService.getSubstituteUserResponse getSubstituteUser(ATOMv0.AuthenticationService.getSubstituteUser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getSubstituteUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ATOMv0.AuthenticationService.getSubstituteUserResponse> getSubstituteUserAsync(ATOMv0.AuthenticationService.getSubstituteUser request);
        
        // CODEGEN: Parameter 'flexwareToken' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="authenticate", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATOMv0.AuthenticationService.InvalidCredentials), Action="authenticate", Name="InvalidCredentials", Namespace="http://flexware.flextronics.com/ws/client/faults/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATOMv0.AuthenticationService.InvalidRequest), Action="authenticate", Name="InvalidRequest", Namespace="http://flexware.flextronics.com/ws/client/faults/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATOMv0.AuthenticationService.AccessDenied), Action="authenticate", Name="AccessDenied", Namespace="http://flexware.flextronics.com/ws/client/faults/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATOMv0.AuthenticationService.ServiceFault), Action="authenticate", Name="ServiceFault", Namespace="http://flexware.flextronics.com/ws/client/faults/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="flexwareToken")]
        ATOMv0.AuthenticationService.authenticateResponse authenticate(ATOMv0.AuthenticationService.authenticate request);
        
        [System.ServiceModel.OperationContractAttribute(Action="authenticate", ReplyAction="*")]
        System.Threading.Tasks.Task<ATOMv0.AuthenticationService.authenticateResponse> authenticateAsync(ATOMv0.AuthenticationService.authenticate request);
        
        // CODEGEN: Generating message contract since the operation getCurrentRelease is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="getCurrentRelease", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATOMv0.AuthenticationService.InvalidRequest), Action="getCurrentRelease", Name="InvalidRequest", Namespace="http://flexware.flextronics.com/ws/client/faults/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATOMv0.AuthenticationService.InvalidToken), Action="getCurrentRelease", Name="InvalidToken", Namespace="http://flexware.flextronics.com/ws/client/faults/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATOMv0.AuthenticationService.ServiceFault), Action="getCurrentRelease", Name="ServiceFault", Namespace="http://flexware.flextronics.com/ws/client/faults/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ATOMv0.AuthenticationService.getCurrentReleaseResponse getCurrentRelease(ATOMv0.AuthenticationService.getCurrentRelease request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getCurrentRelease", ReplyAction="*")]
        System.Threading.Tasks.Task<ATOMv0.AuthenticationService.getCurrentReleaseResponse> getCurrentReleaseAsync(ATOMv0.AuthenticationService.getCurrentRelease request);
        
        // CODEGEN: Parameter 'masterData' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="getMasterData", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATOMv0.AuthenticationService.InvalidRequest), Action="getMasterData", Name="InvalidRequest", Namespace="http://flexware.flextronics.com/ws/client/faults/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATOMv0.AuthenticationService.InvalidToken), Action="getMasterData", Name="InvalidToken", Namespace="http://flexware.flextronics.com/ws/client/faults/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATOMv0.AuthenticationService.ServiceFault), Action="getMasterData", Name="ServiceFault", Namespace="http://flexware.flextronics.com/ws/client/faults/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="masterData")]
        ATOMv0.AuthenticationService.getMasterDataResponse getMasterData(ATOMv0.AuthenticationService.getMasterData request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getMasterData", ReplyAction="*")]
        System.Threading.Tasks.Task<ATOMv0.AuthenticationService.getMasterDataResponse> getMasterDataAsync(ATOMv0.AuthenticationService.getMasterData request);
        
        // CODEGEN: Parameter 'userRoles' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="getUserRoles", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATOMv0.AuthenticationService.InvalidRequest), Action="getUserRoles", Name="InvalidRequest", Namespace="http://flexware.flextronics.com/ws/client/faults/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATOMv0.AuthenticationService.InvalidToken), Action="getUserRoles", Name="InvalidToken", Namespace="http://flexware.flextronics.com/ws/client/faults/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATOMv0.AuthenticationService.ServiceFault), Action="getUserRoles", Name="ServiceFault", Namespace="http://flexware.flextronics.com/ws/client/faults/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="userRoles")]
        ATOMv0.AuthenticationService.getUserRolesResponse getUserRoles(ATOMv0.AuthenticationService.getUserRoles request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getUserRoles", ReplyAction="*")]
        System.Threading.Tasks.Task<ATOMv0.AuthenticationService.getUserRolesResponse> getUserRolesAsync(ATOMv0.AuthenticationService.getUserRoles request);
        
        // CODEGEN: Parameter 'substitutedUsers' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="getSubstitutedUsers", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATOMv0.AuthenticationService.InvalidRequest), Action="getSubstitutedUsers", Name="InvalidRequest", Namespace="http://flexware.flextronics.com/ws/client/faults/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATOMv0.AuthenticationService.InvalidToken), Action="getSubstitutedUsers", Name="InvalidToken", Namespace="http://flexware.flextronics.com/ws/client/faults/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATOMv0.AuthenticationService.ServiceFault), Action="getSubstitutedUsers", Name="ServiceFault", Namespace="http://flexware.flextronics.com/ws/client/faults/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="substitutedUsers")]
        ATOMv0.AuthenticationService.getSubstitutedUsersResponse getSubstitutedUsers(ATOMv0.AuthenticationService.getSubstitutedUsers request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getSubstitutedUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<ATOMv0.AuthenticationService.getSubstitutedUsersResponse> getSubstitutedUsersAsync(ATOMv0.AuthenticationService.getSubstitutedUsers request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSubstituteUser", WrapperNamespace="http://flexware.flextronics.com/ws/client/authentication", IsWrapped=true)]
    public partial class getSubstituteUser {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://flexware.flextronics.com/ws/client/authentication", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATOMv0.AuthenticationService.flexwaretokenws flexwareToken;
        
        public getSubstituteUser() {
        }
        
        public getSubstituteUser(ATOMv0.AuthenticationService.flexwaretokenws flexwareToken) {
            this.flexwareToken = flexwareToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSubstituteUserResponse", WrapperNamespace="http://flexware.flextronics.com/ws/client/authentication", IsWrapped=true)]
    public partial class getSubstituteUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://flexware.flextronics.com/ws/client/authentication", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATOMv0.AuthenticationService.usermasterws substituteUser;
        
        public getSubstituteUserResponse() {
        }
        
        public getSubstituteUserResponse(ATOMv0.AuthenticationService.usermasterws substituteUser) {
            this.substituteUser = substituteUser;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="credentials-ws", Namespace="http://flexware.flextronics.com/ws/client/authentication")]
    public partial class credentialsws : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string solutionCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string solutionCode {
            get {
                return this.solutionCodeField;
            }
            set {
                this.solutionCodeField = value;
                this.RaisePropertyChanged("solutionCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="authenticate", WrapperNamespace="http://flexware.flextronics.com/ws/client/authentication", IsWrapped=true)]
    public partial class authenticate {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://flexware.flextronics.com/ws/client/authentication", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATOMv0.AuthenticationService.credentialsws credentials;
        
        public authenticate() {
        }
        
        public authenticate(ATOMv0.AuthenticationService.credentialsws credentials) {
            this.credentials = credentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="authenticateResponse", WrapperNamespace="http://flexware.flextronics.com/ws/client/authentication", IsWrapped=true)]
    public partial class authenticateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://flexware.flextronics.com/ws/client/authentication", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATOMv0.AuthenticationService.flexwaretokenws flexwareToken;
        
        public authenticateResponse() {
        }
        
        public authenticateResponse(ATOMv0.AuthenticationService.flexwaretokenws flexwareToken) {
            this.flexwareToken = flexwareToken;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://flexware.flextronics.com/ws/client/authentication")]
    public partial class currentReleaseRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private flexwaretokenws flexwareTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public flexwaretokenws flexwareToken {
            get {
                return this.flexwareTokenField;
            }
            set {
                this.flexwareTokenField = value;
                this.RaisePropertyChanged("flexwareToken");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://flexware.flextronics.com/ws/client/authentication")]
    public partial class currentReleaseResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string currentReleaseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string currentRelease {
            get {
                return this.currentReleaseField;
            }
            set {
                this.currentReleaseField = value;
                this.RaisePropertyChanged("currentRelease");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCurrentRelease {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://flexware.flextronics.com/ws/client/authentication", Order=0)]
        public ATOMv0.AuthenticationService.currentReleaseRequest currentReleaseRequest;
        
        public getCurrentRelease() {
        }
        
        public getCurrentRelease(ATOMv0.AuthenticationService.currentReleaseRequest currentReleaseRequest) {
            this.currentReleaseRequest = currentReleaseRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCurrentReleaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://flexware.flextronics.com/ws/client/authentication", Order=0)]
        public ATOMv0.AuthenticationService.currentReleaseResponse currentReleaseResponse;
        
        public getCurrentReleaseResponse() {
        }
        
        public getCurrentReleaseResponse(ATOMv0.AuthenticationService.currentReleaseResponse currentReleaseResponse) {
            this.currentReleaseResponse = currentReleaseResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="master-data-element-ws", Namespace="http://flexware.flextronics.com/ws/client/authentication")]
    public partial class masterdataelementws : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string nameField;
        
        private masterdataobjectws[] objectsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("objects", IsNullable=true, Order=2)]
        public masterdataobjectws[] objects {
            get {
                return this.objectsField;
            }
            set {
                this.objectsField = value;
                this.RaisePropertyChanged("objects");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="master-data-object-ws", Namespace="http://flexware.flextronics.com/ws/client/authentication")]
    public partial class masterdataobjectws : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string codeField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string activeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("active");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMasterData", WrapperNamespace="http://flexware.flextronics.com/ws/client/authentication", IsWrapped=true)]
    public partial class getMasterData {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://flexware.flextronics.com/ws/client/authentication", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATOMv0.AuthenticationService.flexwaretokenws flexwareToken;
        
        public getMasterData() {
        }
        
        public getMasterData(ATOMv0.AuthenticationService.flexwaretokenws flexwareToken) {
            this.flexwareToken = flexwareToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMasterDataResponse", WrapperNamespace="http://flexware.flextronics.com/ws/client/authentication", IsWrapped=true)]
    public partial class getMasterDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://flexware.flextronics.com/ws/client/authentication", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("masterData")]
        public ATOMv0.AuthenticationService.masterdataelementws[] masterData;
        
        public getMasterDataResponse() {
        }
        
        public getMasterDataResponse(ATOMv0.AuthenticationService.masterdataelementws[] masterData) {
            this.masterData = masterData;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="user-roles-ws", Namespace="http://flexware.flextronics.com/ws/client/authentication")]
    public partial class userrolesws : object, System.ComponentModel.INotifyPropertyChanged {
        
        private usermasterws userMasterField;
        
        private solutionrolews[] rolesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public usermasterws userMaster {
            get {
                return this.userMasterField;
            }
            set {
                this.userMasterField = value;
                this.RaisePropertyChanged("userMaster");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("roles", IsNullable=true, Order=1)]
        public solutionrolews[] roles {
            get {
                return this.rolesField;
            }
            set {
                this.rolesField = value;
                this.RaisePropertyChanged("roles");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="solution-role-ws", Namespace="http://flexware.flextronics.com/ws/client/authentication")]
    public partial class solutionrolews : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserRoles", WrapperNamespace="http://flexware.flextronics.com/ws/client/authentication", IsWrapped=true)]
    public partial class getUserRoles {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://flexware.flextronics.com/ws/client/authentication", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATOMv0.AuthenticationService.flexwaretokenws flexwareToken;
        
        public getUserRoles() {
        }
        
        public getUserRoles(ATOMv0.AuthenticationService.flexwaretokenws flexwareToken) {
            this.flexwareToken = flexwareToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserRolesResponse", WrapperNamespace="http://flexware.flextronics.com/ws/client/authentication", IsWrapped=true)]
    public partial class getUserRolesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://flexware.flextronics.com/ws/client/authentication", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATOMv0.AuthenticationService.userrolesws userRoles;
        
        public getUserRolesResponse() {
        }
        
        public getUserRolesResponse(ATOMv0.AuthenticationService.userrolesws userRoles) {
            this.userRoles = userRoles;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSubstitutedUsers", WrapperNamespace="http://flexware.flextronics.com/ws/client/authentication", IsWrapped=true)]
    public partial class getSubstitutedUsers {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://flexware.flextronics.com/ws/client/authentication", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATOMv0.AuthenticationService.flexwaretokenws flexwareToken;
        
        public getSubstitutedUsers() {
        }
        
        public getSubstitutedUsers(ATOMv0.AuthenticationService.flexwaretokenws flexwareToken) {
            this.flexwareToken = flexwareToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSubstitutedUsersResponse", WrapperNamespace="http://flexware.flextronics.com/ws/client/authentication", IsWrapped=true)]
    public partial class getSubstitutedUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://flexware.flextronics.com/ws/client/authentication", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("substitutedUsers", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATOMv0.AuthenticationService.usermasterws[] substitutedUsers;
        
        public getSubstitutedUsersResponse() {
        }
        
        public getSubstitutedUsersResponse(ATOMv0.AuthenticationService.usermasterws[] substitutedUsers) {
            this.substitutedUsers = substitutedUsers;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface authenticationPortChannel : ATOMv0.AuthenticationService.authenticationPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class authenticationPortClient : System.ServiceModel.ClientBase<ATOMv0.AuthenticationService.authenticationPort>, ATOMv0.AuthenticationService.authenticationPort {
        
        public authenticationPortClient() {
        }
        
        public authenticationPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public authenticationPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public authenticationPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public authenticationPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATOMv0.AuthenticationService.getSubstituteUserResponse ATOMv0.AuthenticationService.authenticationPort.getSubstituteUser(ATOMv0.AuthenticationService.getSubstituteUser request) {
            return base.Channel.getSubstituteUser(request);
        }
        
        public ATOMv0.AuthenticationService.usermasterws getSubstituteUser(ATOMv0.AuthenticationService.flexwaretokenws flexwareToken) {
            ATOMv0.AuthenticationService.getSubstituteUser inValue = new ATOMv0.AuthenticationService.getSubstituteUser();
            inValue.flexwareToken = flexwareToken;
            ATOMv0.AuthenticationService.getSubstituteUserResponse retVal = ((ATOMv0.AuthenticationService.authenticationPort)(this)).getSubstituteUser(inValue);
            return retVal.substituteUser;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ATOMv0.AuthenticationService.getSubstituteUserResponse> ATOMv0.AuthenticationService.authenticationPort.getSubstituteUserAsync(ATOMv0.AuthenticationService.getSubstituteUser request) {
            return base.Channel.getSubstituteUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ATOMv0.AuthenticationService.getSubstituteUserResponse> getSubstituteUserAsync(ATOMv0.AuthenticationService.flexwaretokenws flexwareToken) {
            ATOMv0.AuthenticationService.getSubstituteUser inValue = new ATOMv0.AuthenticationService.getSubstituteUser();
            inValue.flexwareToken = flexwareToken;
            return ((ATOMv0.AuthenticationService.authenticationPort)(this)).getSubstituteUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATOMv0.AuthenticationService.authenticateResponse ATOMv0.AuthenticationService.authenticationPort.authenticate(ATOMv0.AuthenticationService.authenticate request) {
            return base.Channel.authenticate(request);
        }
        
        public ATOMv0.AuthenticationService.flexwaretokenws authenticate(ATOMv0.AuthenticationService.credentialsws credentials) {
            ATOMv0.AuthenticationService.authenticate inValue = new ATOMv0.AuthenticationService.authenticate();
            inValue.credentials = credentials;
            ATOMv0.AuthenticationService.authenticateResponse retVal = ((ATOMv0.AuthenticationService.authenticationPort)(this)).authenticate(inValue);
            return retVal.flexwareToken;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ATOMv0.AuthenticationService.authenticateResponse> ATOMv0.AuthenticationService.authenticationPort.authenticateAsync(ATOMv0.AuthenticationService.authenticate request) {
            return base.Channel.authenticateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ATOMv0.AuthenticationService.authenticateResponse> authenticateAsync(ATOMv0.AuthenticationService.credentialsws credentials) {
            ATOMv0.AuthenticationService.authenticate inValue = new ATOMv0.AuthenticationService.authenticate();
            inValue.credentials = credentials;
            return ((ATOMv0.AuthenticationService.authenticationPort)(this)).authenticateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATOMv0.AuthenticationService.getCurrentReleaseResponse ATOMv0.AuthenticationService.authenticationPort.getCurrentRelease(ATOMv0.AuthenticationService.getCurrentRelease request) {
            return base.Channel.getCurrentRelease(request);
        }
        
        public ATOMv0.AuthenticationService.currentReleaseResponse getCurrentRelease(ATOMv0.AuthenticationService.currentReleaseRequest currentReleaseRequest) {
            ATOMv0.AuthenticationService.getCurrentRelease inValue = new ATOMv0.AuthenticationService.getCurrentRelease();
            inValue.currentReleaseRequest = currentReleaseRequest;
            ATOMv0.AuthenticationService.getCurrentReleaseResponse retVal = ((ATOMv0.AuthenticationService.authenticationPort)(this)).getCurrentRelease(inValue);
            return retVal.currentReleaseResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ATOMv0.AuthenticationService.getCurrentReleaseResponse> ATOMv0.AuthenticationService.authenticationPort.getCurrentReleaseAsync(ATOMv0.AuthenticationService.getCurrentRelease request) {
            return base.Channel.getCurrentReleaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<ATOMv0.AuthenticationService.getCurrentReleaseResponse> getCurrentReleaseAsync(ATOMv0.AuthenticationService.currentReleaseRequest currentReleaseRequest) {
            ATOMv0.AuthenticationService.getCurrentRelease inValue = new ATOMv0.AuthenticationService.getCurrentRelease();
            inValue.currentReleaseRequest = currentReleaseRequest;
            return ((ATOMv0.AuthenticationService.authenticationPort)(this)).getCurrentReleaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATOMv0.AuthenticationService.getMasterDataResponse ATOMv0.AuthenticationService.authenticationPort.getMasterData(ATOMv0.AuthenticationService.getMasterData request) {
            return base.Channel.getMasterData(request);
        }
        
        public ATOMv0.AuthenticationService.masterdataelementws[] getMasterData(ATOMv0.AuthenticationService.flexwaretokenws flexwareToken) {
            ATOMv0.AuthenticationService.getMasterData inValue = new ATOMv0.AuthenticationService.getMasterData();
            inValue.flexwareToken = flexwareToken;
            ATOMv0.AuthenticationService.getMasterDataResponse retVal = ((ATOMv0.AuthenticationService.authenticationPort)(this)).getMasterData(inValue);
            return retVal.masterData;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ATOMv0.AuthenticationService.getMasterDataResponse> ATOMv0.AuthenticationService.authenticationPort.getMasterDataAsync(ATOMv0.AuthenticationService.getMasterData request) {
            return base.Channel.getMasterDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<ATOMv0.AuthenticationService.getMasterDataResponse> getMasterDataAsync(ATOMv0.AuthenticationService.flexwaretokenws flexwareToken) {
            ATOMv0.AuthenticationService.getMasterData inValue = new ATOMv0.AuthenticationService.getMasterData();
            inValue.flexwareToken = flexwareToken;
            return ((ATOMv0.AuthenticationService.authenticationPort)(this)).getMasterDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATOMv0.AuthenticationService.getUserRolesResponse ATOMv0.AuthenticationService.authenticationPort.getUserRoles(ATOMv0.AuthenticationService.getUserRoles request) {
            return base.Channel.getUserRoles(request);
        }
        
        public ATOMv0.AuthenticationService.userrolesws getUserRoles(ATOMv0.AuthenticationService.flexwaretokenws flexwareToken) {
            ATOMv0.AuthenticationService.getUserRoles inValue = new ATOMv0.AuthenticationService.getUserRoles();
            inValue.flexwareToken = flexwareToken;
            ATOMv0.AuthenticationService.getUserRolesResponse retVal = ((ATOMv0.AuthenticationService.authenticationPort)(this)).getUserRoles(inValue);
            return retVal.userRoles;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ATOMv0.AuthenticationService.getUserRolesResponse> ATOMv0.AuthenticationService.authenticationPort.getUserRolesAsync(ATOMv0.AuthenticationService.getUserRoles request) {
            return base.Channel.getUserRolesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ATOMv0.AuthenticationService.getUserRolesResponse> getUserRolesAsync(ATOMv0.AuthenticationService.flexwaretokenws flexwareToken) {
            ATOMv0.AuthenticationService.getUserRoles inValue = new ATOMv0.AuthenticationService.getUserRoles();
            inValue.flexwareToken = flexwareToken;
            return ((ATOMv0.AuthenticationService.authenticationPort)(this)).getUserRolesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATOMv0.AuthenticationService.getSubstitutedUsersResponse ATOMv0.AuthenticationService.authenticationPort.getSubstitutedUsers(ATOMv0.AuthenticationService.getSubstitutedUsers request) {
            return base.Channel.getSubstitutedUsers(request);
        }
        
        public ATOMv0.AuthenticationService.usermasterws[] getSubstitutedUsers(ATOMv0.AuthenticationService.flexwaretokenws flexwareToken) {
            ATOMv0.AuthenticationService.getSubstitutedUsers inValue = new ATOMv0.AuthenticationService.getSubstitutedUsers();
            inValue.flexwareToken = flexwareToken;
            ATOMv0.AuthenticationService.getSubstitutedUsersResponse retVal = ((ATOMv0.AuthenticationService.authenticationPort)(this)).getSubstitutedUsers(inValue);
            return retVal.substitutedUsers;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ATOMv0.AuthenticationService.getSubstitutedUsersResponse> ATOMv0.AuthenticationService.authenticationPort.getSubstitutedUsersAsync(ATOMv0.AuthenticationService.getSubstitutedUsers request) {
            return base.Channel.getSubstitutedUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<ATOMv0.AuthenticationService.getSubstitutedUsersResponse> getSubstitutedUsersAsync(ATOMv0.AuthenticationService.flexwaretokenws flexwareToken) {
            ATOMv0.AuthenticationService.getSubstitutedUsers inValue = new ATOMv0.AuthenticationService.getSubstitutedUsers();
            inValue.flexwareToken = flexwareToken;
            return ((ATOMv0.AuthenticationService.authenticationPort)(this)).getSubstitutedUsersAsync(inValue);
        }
    }
}
