//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATOMv0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CISTestResultSet
    {
        public int id { get; set; }
        public string CustomerName { get; set; }
        public string SiteName { get; set; }
        public string BaaNCompanyCode { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<int> TestID { get; set; }
        public string PartNumber { get; set; }
        public string PartRevision { get; set; }
        public string StationName { get; set; }
        public string StationType { get; set; }
        public string LineName { get; set; }
        public Nullable<bool> IsPass { get; set; }
        public Nullable<int> TestGeneration { get; set; }
        public Nullable<System.DateTime> TestTime { get; set; }
        public Nullable<System.DateTime> DataRecvTime { get; set; }
        public Nullable<byte> ProcessStatus { get; set; }
    }
}
