//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATOMv0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimProductLine
    {
        public DimProductLine()
        {
            this.DimProductNumbers = new HashSet<DimProductNumber>();
        }
    
        public int id { get; set; }
        public string ProductLineName { get; set; }
        public Nullable<int> KeyBusinessPartner { get; set; }
    
        public virtual DimBusinessPartner DimBusinessPartner { get; set; }
        public virtual ICollection<DimProductNumber> DimProductNumbers { get; set; }
    }
}
