//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATOMv0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimProcessType
    {
        public DimProcessType()
        {
            this.DimBuckets = new HashSet<DimBucket>();
        }
    
        public int id { get; set; }
        public string ProcessTypeName { get; set; }
    
        public virtual ICollection<DimBucket> DimBuckets { get; set; }
    }
}
