//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATOMv0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metric
    {
        public Metric()
        {
            this.MetricConfigurations = new HashSet<MetricConfiguration>();
        }
    
        public int id { get; set; }
        public string MetricName { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<MetricConfiguration> MetricConfigurations { get; set; }
    }
}
