//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATOMv0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTYbyDay
    {
        public System.DateTime RTYDate { get; set; }
        public string BusinessPartner { get; set; }
        public string StationBucket { get; set; }
        public string PartFamilyID { get; set; }
        public Nullable<decimal> RTY { get; set; }
        public Nullable<int> RTYYear { get; set; }
        public string RTYMonth { get; set; }
        public Nullable<int> RTYDay { get; set; }
        public Nullable<int> MonthNo { get; set; }
        public string SiteID { get; set; }
        public Nullable<int> ProdVol { get; set; }
        public string TopFPYStationName5 { get; set; }
        public Nullable<decimal> TopFPY5 { get; set; }
        public string TopFPYStationName4 { get; set; }
        public Nullable<decimal> TopFPY4 { get; set; }
        public string TopFPYStationName3 { get; set; }
        public Nullable<decimal> TopFPY3 { get; set; }
        public string TopFPYStationName2 { get; set; }
        public Nullable<decimal> TopFPY2 { get; set; }
        public string TopFPYStationName1 { get; set; }
        public Nullable<decimal> TopFPY1 { get; set; }
    }
}
